### ISSUE TITLE
json log formatter cannot handle data and exception

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-log#26]
test example:

```
  const ex = new Error('Hello World');
  ex.stack = 'Not a stack';
  ex.code = 42;
  ck('error', ['Wubalubadubdub', { bar: 32 }, ex], {
    bar: 32.
    message: 'Wubalubadubdub',
    level: 'error',
    exception: {
      $type: 'Error',
      name: 'Error',
      message: 'Hello World',
      stack: 'Not a stack',
      code: 42,
    },
  });
```

but generates:

```
{
  exception: {
    '$type': 'Error',
    code: 42,
    message: 'Hello World',
    name: 'Error',
    stack: 'Not a stack'
  },
  level: 'error',
  message: 'Wubalubadubdub { ' +
    'bar: 32 }'
}
```

**Comment by koraa** [comment]
This is pretty much by design; the jsonMessageFormatter treats the last parameter as potentially containing json; exceptions are handled as a special case so they can be serialized with a standard format (and so you can do searches for "give me all messages with the exception flag set").

We could as you suggested expand the heuristic to include the field next-to-the-last one if the last field is an exception…however I am a bit weary of doing that, because as I said in another issue I am not extremely happy with the json/data heuristic in the first place and doing this would introduce some tough question (can the exception be second to last? What if the data contains an "exception" field?);

I think this would be mostly useful for people who have decided to actively utilize the data logging features, so they could just write: `error('Wubalubadubdub', { exception: error, bar: 42 })`.

I realize this is not what you wanted, but I hope it is sufficient for your specific use case!

**Comment by tripodsan** [comment]
what about ditching the last-field-heuristic and _only_ provide extra json data with chaining?

for example (I don't think this is implementable this way without delaying the logging) 
```js
error('this is not good', e).data({ reactor.temp: 4325 });
```

or simpler:
```js
error.data({ reactor.temp: 4325 })('this is not good', e);
```

**Comment by koraa** [comment]
I'll have to think about this for a bit…
My immediate thought is that I would rather not complicate the interface in such a way, but let's ponder it for a while…

**Comment by tripodsan** [comment]
Another option would be to use the same behaviour as bunyan:
if the 1st object is a plain object, use it as data-fields.
