### ISSUE TITLE
define 'LogFacade' interface that acts like a winston / bunyan logger

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-log#30]
### problem 1 - code style
helix-log promises to be very simple to use, by setting up global default logging.
however, when trying to keep the code clean (eslint), one tends to avoid unused imports (requires).

so imagine my code uses `debug` and `info` so far. so I have this import:
```
const { debug, info } = require('@adobe/helix-log');
```
now, I want to use a `warn()`, so I need to add it to the imports. later I decided to change the `warn` to an `error`, so I need to change (and clean up) the imports again.

for me, it would be way easier to just have `log.*` object, like `console`, that offers all levels. this would also let my IDE offer autocomplete. Furthermore, a problem that can happen during refactoring is that a `info` variable might already be defined locally and will clash with the global `info()` function.

### problem 2 - sub loggers
a cool feature of bunyan are the child loggers, especially when dealing with json based log formats. they allow to bind a set of log fields to a logger instance. see https://github.com/trentm/node-bunyan#logchild.

AFAICS, the current logic is:
1. capture the log message parameters 
2. use the formatter to convert it to a string or object
3. send it to the destination (file, console, http)

I think, having `fields` as a first class concept would allow for more versatile logging:
1. capture the log message parameters
2. create a log-data object using the message parameters, level, etc.
3. use the formatter to serialize a `message` field.
4. send the data to the destination. the destination can still decide either to include the entire log-data or just parts of it.

### problem 3 - log level sensitive logging
currently, each logger has its own log-level setting. this is good, because I might want to send debug logs to the file logger, but not the console logger.
on the other hand, the developer might want to not create certain logs at all, if a the log level is low. eg. don't include stack traces if not debug log-level. somehow there should be a way to accomplish both. maybe this is not so important, though.

----

## Suggestion

- Create a new class `LogFacade` (or something) that holds a map of `fields`
- the `LogFacade.logWithOpts()` would generate a `log-data` object with the `message` (array) and the `opts`. it would also add the `fields` to the `log-data`
- the `LogFacade` would also contain methods for `debug|info|warn|error|etc`, which just delegate to the `logWithOpts` and the respective `level`.
- the method `LogFacade.child(subFields)` would create a sub-facade, overlaying the parent `fields` with the `subFields` for this instance.
- the `rootFacade` would be a default instance of `LogFacade`, using the `rootLogger`.
- `helix-log` would export `log` as the `rootFacade`

### Alternative
follow bunyans naming and:
- rename the `Logger` interface to `LogStream`
- rename the `LogFacade` to `Logger`

**Comment by tripodsan** [comment]
btw, I also like the https://www.npmjs.com/package/bunyan#serializers concept of bunyan. it allows to map any java-script option to a json representation.

**Comment by koraa** [comment]
```
btw, I also like the https://www.npmjs.com/package/bunyan#serializers concept of bunyan. it allows to map any java-script option to a json representation.
```

I though I had built something even more generic with the combination of helix log formatters and the trait based json serializer? Is there anything that can be done with bunyan serializers but not with helix-log formatters? I would like to know so I can fix that blunder!

The `JsonifyForLog` trait can be used to define serialization functions for any type; the following example shows a custom type with fully customized javascript & debug printing formatting…

```
const util = require('util');
const { JsonifyForLog } = require('@adobe/helix-log');
class MyCustomType {
  // Customize the normal debug printing used by text formatters
  [util.inspect.custom]() {
    return "My Custom Type is Awesome!";
  }

  // Customize the json formatter
  [JsonifyForLog.sym]() {
    return {
      "cheese": "awesome",
      "myCustomType": "awesome"
    };
  }
}
```

The ferrum trait system features even more advanced features, like implementing the JsonifyForLog for external types (e.g. from a library), values (null or 42 or Symbol('foo')) or even wildcard type and value matchers…

This is not the same as bunyans serializers mechanism, but that can be achieved using formatters; I haven't thus far considered adding this as a stock feature because there is a bit of a danger that someone, somewhere logs a completely different type with a field name that was configured with a very specific serializer (so it's not extremely robust) and IMHO for 99% of use cases type based serialization is more powerful anyways.

```
const { empty, type, last, shallowcopy, iter, initial } = require('ferrum');

const messageFormatJsonSpecialField = (fieldSerializers) => (msg, opts) => {
  if (empty(msg) || type```
const messageFormatJsonSpecialFieldSnowflake = (fieldFormatters) => (msg, opts) => {
  if (!empty(msg) || type(last(msg)) === Object) {
    return messageFormatJson(msg, opts);
  }
};
```
(last(msg)) !== Object) {
    return messageFormatJson(msg, opts);
  }

  const data = shallowcopy(last(msg));

  for (const [k, v] of iter(data)) {
    if (k in fieldSerializers) {
      data[k] = fieldSerializers[k](v);
    }
  };

  return messageFormatJson([...initial(msg), data], opts);
};
```

The formatter feature in helix-log is designed to allow arbitrary transformations to be performed on the message (as long as they are not async…).

**Comment by koraa** [comment]
```
for me, it would be way easier to just have log.* object, like console, that offers all levels. this would also let my IDE offer autocomplete. Furthermore, a problem that can happen during refactoring is that a info variable might already be defined locally and will clash with the global info() function.
```

Why not just use `const log = require('@adobe/helix-log');`? I prefer the more functional style of importing each method by itself (and I usually just remember function names like `warn`), but it's in no way a requirment…

**Comment by koraa** [comment]
> problem 2 - sub loggers

Not sure I entirely understand that one. Could you provide a couple of examples "current way of doing this/proposed way of doing this" so I could understand the proposed interface better?

**Comment by koraa** [comment]
> problem 3 - log level sensitive logging

Sounds like a good idea…I think this is only relevant for the file logger atm? We could just lazily open the file to achieve that…I'd be happy to take a pull request that introduce a "lazy open" option for the file logger…

**Comment by koraa** [comment]
> I think, having fields as a first class concept would allow for more versatile logging:
> Create a new class LogFacade (or something) that holds a map of fields

Hmm. Hmm. Hmm. Not sure, I have to think about this.
Bunyan is very opinionated about the "fields as first class objects" concept; in helix-log explicitly decided not to to this in order to avoid the "my logs are all json and I can't see anything" fiasco from bunyan and because most logging in helix was not field oriented.
On the other hand with the move to coralogix/alternatives we will want to do more field based logging and a feature adding a  field for logging to all loggers would be highly useful. I would like to be able to add such a feature.
The entire field handling sticks out like a sore thumb from helix-log; your own pr to add the openwhisk activation fields exemplify this; but I don't want to go the bunyan way either, your own PR to remove bunyan fields for the ConsoleLogger shows that much.

We must also consider that there are multiple types of fields: There are fields that are central to the content of the message (like the exception field); there are fields which really just contain information about the context the message occurs in (like the http request id in an http server) and some information that is entirely redundant in certain contexts (like printing the hostname in a console logger – like we don't know that when we start a program in the console).

The first two classes of fields should be provided, the third should be hidden; but what class a field fits into differs by logger and sometimes is not automatically decidable and the user should actively decide to hide that info…

Not sure about your proposal; it looks a bit complicated and like it errs very much on the bunyan side of things and we must find the middle ground here…

I want a solution for this, but lets take enough time to ponder this!

**Comment by tripodsan** [comment]
> fields... "my logs are all json and I can't see anything" 

I don't think that there should be a difference between log metatdata, and log data. you can define a certain set of fields as reserverd, like `level`, `message`, `exception`, `timestamp`. but if the _log-data_. as long as the default formatters / serializers for file and console logging produce a reasonable log line, it's all transparent for the user.

I think the current behaviour is more confusing, if you want to have both, augmented log-data for a JSON aware log-stream, and also console like messages.

**Comment by tripodsan** [comment]
> sub-loggers

see the examples in bunyan: https://github.com/trentm/node-bunyan#logchild

assuming that i don't use the `rootLogger`, I would do:

```
const log = rootLogger.child({
  requestId: ....,
  activationId: ...,
});
```

which would create a logger instance which bound fields. this is especially useful in concurrent environments (openwhisk actions, or http request handling).

**Comment by tripodsan** [comment]
> re serializers

(your code example above is ill-formatted, I can't really understand the code)

 can you give an example on how to create a serialization for a type I don't own? for example for `http.request` ?

see the bunyan example: https://github.com/trentm/node-bunyan/blob/fe31b83e42d9c7f784e83fdcc528a7c76e0dacae/lib/bunyan.js#L1088-L1097

**Comment by koraa** [comment]
The formatting is now fixed; please refer to the ferrum documentation for further info on how to use traits: https://www.ferrumjs.org/module-trait-Trait.html
