### ISSUE TITLE
Bump up log messages timestampto microsecond precision

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-log#43]
AFAICS, the CoralogixLogger uses phin to POST the log message to the coralogix API, but does not wait for them to complete. they might arrive out of order at their backend.

see https://github.com/adobe/helix-log/blob/79e3e18068779003cdc2f7339cc4eba268e8463f/src/coralogix.js#L132

since the timestamp is only millisecond precise, this could result in a garbled log stream.
suggest to either ensure that the log messages are sent in sequence or increase the precision of the timestamp.

or maybe it would be better to use [the coralogix client](https://github.com/coralogix/nodejs-coralogix-sdk) which buffers and sends log messages in bulk.

**Comment by koraa** [comment]
I have posted the question to coralogix; I am not sure how their system behaves for multiple log messages in the same millisecond; the ordering might just be undefined.
I've asked them whether it would be possible to add a decimal component to the timestamp. That would allow for nanosecond precision or even better…

**Comment by koraa** [comment]
Btw, I am intentionally avoiding the Coralogix API client, because (1) it has a dependency to request (which is humongous), (2) it drops messages when there are too many coming in (3) it does not perform error isolation (4) it infinitly retries sending buffers on error (5) it can only have one request in flight at a time…

I initially had a coralogix logger sending data in bulk, but ran into the error isolation problem…I'd like to know what coralogix reccomend before I reintroduce a bulk logger again…
