### ISSUE TITLE
Coralogix API_KEY leaked in error message

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-log#44]
in case of an error in a formatter, the multilogger reports an error, leaking the API_KEY:

```
MultiLogger encountered exception while logging to CoralogixLogger - CoralogixLogger { apikey: 'hidden-xxxx-f8dd-b196-b7b7b83fe38f', apiurl: 'https://api.coralogix.com/api/v1/', app: 'myapp', subsystem: 'bot', host: '3924f26b366d', level: 'info', formatter: [Function: formatter], fmtOpts: {} } :
```

**Comment by koraa** [comment]
Yes; good catch.

(BTW, your dump above still leaks 64 or the 127 bits of entropy in the UUID; if this is from the original token I would generate a new one).

We should definitely introduce a type for hiding secrets:

```
const { defineProperty } = Object;
const { inspect } = require('util');

class Secret {
  constructor(value) {
    Object.defineProperty(this, 'secret', {
      enumerable: false,
      value: '1234',
      writable: true
    });
  }

  [inspect.custom]() {
    return "[Hidden Secret]"
  }

  toString() {
    return "[Hidden Secret]";
  }
};
```

This basically just makes sure that the author of code must be explicit about using the secret; (almost; for I cannot no if there are ops I haven't thought about) no operation should expose the secret or use it in another way unless the dev was explicit about extracting the secret (mySecret.secret). By using .secret as a field name every developer should also know that they are using secret data.

This strategy IMHO beats just making sure we never log anything that could contain a secret because that's just too much eventualities to consider… (it's far easier to think about security whenever you are working with secrets than whenever you are doing any logging).

Unfortunately this method is not foolproof and will IMO never provide complete coverage: It relies on our whole code base using this method (which will be hard enough to ensure), it also relies our customers using this mechanism in their code (ugh, probably not going to happen) and it requires third party libs to use such a mechanism (not going to happen)…

This is the reason I insist on whatever logging service we use being *very secure*.

**Comment by tripodsan** [comment]
> We should definitely introduce a type for hiding secrets:

could that be something to add to ferrum ?

**Comment by koraa** [comment]
The scope of ferrum is very limited; I don't think it would be the best fit; I'd just add it to this repo…

**Comment by tripodsan** [comment]
ok. please do....
